username: ENC[AES256_GCM,data:8sDTZmU=,iv:qmSZbIoSh+YRqtYbSN48gLSbcoC9JoqMhAn7HKRzUrA=,tag:ClBvdg/RqTlt3e096E9Bxw==,type:str]
password: ENC[AES256_GCM,data:LnIwn2KluBUMsGh4J4cAhw==,iv:wna5Xpp3ziCjWMCfwOdA4CKTjpFt0PiRc1ZOuzloV+U=,tag:LuygDnMNY4mFEieVyH7crA==,type:str]
bcrypt_hash: ENC[AES256_GCM,data:voR0nkSrsmJGszhCFDmBx+CCkMkx90OCnQLZSnAG0s6rfOn0FS/oQIMmodjP8a839rT5Nc83k+dYaZsv,iv:5isgummMdDkDDHFiiuMQy3xQUw+YUu3gNdbOUvl/Zic=,tag:uz3JJkRd9gmj7XklWHqPxQ==,type:str]
password_mtime: ENC[AES256_GCM,data:hUlRVOA8aDm5JDA6NpGmSqteOZk=,iv:4ZggXuof8QNtUPSutJ72K+qIUeuXfc69YBKEyTBdQ94=,tag:gHkzouJkgAcbQbwb7yj+6Q==,type:time]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbzltTzVaU2trRlNRa1Uy
            WDRiSnNQSkFLTG5xaHErekVYUW9ZcDNHM2xVClNJUzNTMFJrZ0NVWkFUbWFsL05F
            VHpGTDdGODhPZ3k2ZVluTGZiUHh4ZGsKLS0tIDcrajgyUWEzbWZWUFdwRUxFMzM5
            OWpSS1dmM081QUdtNDB5SG9YblVBVGMK87RYV7iB0XcDR5bw2Y1qtHMmUznF3lb8
            +W1Zi3fUYIXuykdZlUzx895kc52BKqhNRDx2yXNEzw5E+kbSVZej+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-10T00:31:39Z"
    mac: ENC[AES256_GCM,data:6HYT0PoNKnPK/3rCDWO7jGXZLrOHFFhLY3PZbsj7x88iCCK3e6xXZzbpe5D+eC5FbzYhW/clhMB4S5wJhHTI6pLyZw5gxp/IOP3F4x8swdXStcLnPjeoyCVjLiX14IT0qfl/9NQ9c3HUryApT0ojxwAVvW36HVFsERlcAEATZkk=,iv:2l8zvgl3/ZIv09QnXfoMV8oQDM26K/qkR+PG2IrvCys=,tag:Ur54kEw3Ea5OEPj5k4yTHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
