username: ENC[AES256_GCM,data:DqPwt+I=,iv:yvcBcr3mvY/m0FVukeCld5E5ZY0Ruh+6p5q0YcK2znI=,tag:HcmOFXgKYtv0X2hvjyfSMA==,type:str]
password: ENC[AES256_GCM,data:xJTP0rQ6JWzVQGLOdJyhO5PKEmE=,iv:EkcB0mqxijYfijM8dW1Cn7oKasSdvtx2JdiI0Wvc3Ms=,tag:J3kC3VJR2dxyy1OkwJQrTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzL04vYks4RnlHcnJuTC9z
            K3M0RVVxNC9aTXY1M1JtcXNQUEdaZ0hYVVEwCk9JUkN3VzlCZUEvYzFkNDdCY2tz
            aVRHNHJSeVlueHZ3aVFaTG50WDF0a3cKLS0tIE8wNUU2ak5nUzcyaFgxblNKd2xa
            V204Lzg4OVFTaDNjYWJPQWo0bldGTTAKBEoKjadN9mVtjKfsMxfpNGw2Xq7xgoiP
            vrmH5JJxd2gRBdzvXRGv92iTHCNouthxmSENxgt8vNghIVGMT5VPAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-06T07:17:17Z"
    mac: ENC[AES256_GCM,data:ZRklx32MII7eEugaTgdcTBiy4S5p1VSKYHkRsfavnIX3ADrcyIoEwM5SQqhgaXaJwxanyKhxY5TYyHhOtQaYvWlLh0UPOEIKiVPfMgglB/Zp6HSvwaQY5lderPHQWPH6Z7794AaGR38lSXnGORK0Vo6pOJZ9Ur1Ft7wKJex8L14=,iv:TE2erIgsGP0wePinDmwQdNKHpip2JKAtDRq8q81q/x4=,tag:+KWwQGrw6VsR6Z6DtzpYBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
