username: ENC[AES256_GCM,data:ZExBeDg=,iv:1o0dVZG6aqW1CC4uWmtOf0ruCZXNpHr56pYvDiMbqi4=,tag:4jMqOolZ45ein2vmy4x/xQ==,type:str]
password: ENC[AES256_GCM,data:Dz7hln7nRVVyukpksJ/e5KN2az4=,iv:58Am05wA2qx9Hd//yR/b/QIu8RGYS33ox39FGI2vQsE=,tag:jsUXnHIemuhv9Q3zXU6Vfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVDliQTdsVUszWmdZL1Bo
            cTdDRmZMUDVBbjIrOGRMYktTRnJHbm83UnprCklwUmlYdGZPd2dxckhrOWJub1R2
            Y1pEalY1SDNlRHpzaGQrRHczcDhOSk0KLS0tIEJsM3JBME84RG9FZUhzdU1KemtY
            UFJuVXRpcGtDK2ZJN1RLUXB0UENFWm8KgJJ+wHu/06baa5CZD/HuIyjCmuVOFH4E
            BUKc7KPMYKnNykAulueKiCtwNZh7WlsMqV8nRhswp+VNerzswpOBqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-06T07:23:46Z"
    mac: ENC[AES256_GCM,data:vz4CSg7ae+yZj1Vgo432xUy2/mpLGJlYs8tQyQae+2IF/8QJvOVkgKu/AfXzyRJuXcmjk2ctIat4f08PH0hBZeqXF/pUI+fq+C1f7otQ4SBEQ/DvnMBwWGB+ukIGCIQ1Urj9OMtsdWPm+qJeeB4Zi+qxZ3QsRdViSRAOFf5MECw=,iv:eQKQU3Lp4ZP4lTa0yaQJ/xith51aCqNKuPKnXwBZfsQ=,tag:z3sG87a/bKmV+bbIfpYQ3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
