password_hash: ENC[AES256_GCM,data:GSnEKf7/t8moDaxkuLHpNYmS5jmBpCRDHJeNhfgrpmKktUK820m7AIZyOFGHfIAAvubNi/5zwrhwqrCf,iv:s5U9xHdXfbcPKjdcpqDJQGfZpSokqjV3vH0Rcm/hae4=,tag:kNvG087+EG8k4LI2s4ny+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUVpRMVpaVE9iUnBCaEE3
            NkdnNFZiZW9TWVRsSTFIeUxWMEhWSWw4VkZVCldubTlCU015anhIZjhZSnhGMUEr
            WmZ1bVhoZWtkdyttdmhzb1U5aXJCK1UKLS0tIEc1WXpvVFNjOVBWK05yMEJoR09Q
            cXRuYlZrMUlSeUdHQVlQZHJ2VGtHSzAKcPZV/fVxsUiev1gir/atfLH0hGtIHgju
            OgaC8CaP9ayTOoOjvJN/MbT4jgJ5H6n6j5mJ4dqjeptUDrBjPSz/YA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-11T03:09:57Z"
    mac: ENC[AES256_GCM,data:YxMibuL3LUL5gWUHHmXZNY+YtCBfTCnK9k80iAiJOOhpT84zu/wX5c/gJs5e2eqYCIhkGyoOxwbCQ0n58JVhpIkCXyJeOG08hHHAjDU2Rr8qtAiDzxa5B5IJ+eAtzx+2o6mCbWMq4Sl912rYHpqeeAfcW0tUNWAQy72uC5FQ4wc=,iv:3LwbZ9pofiubF59nUiMCcF49QH0CCgFkpPoca4clTUM=,tag:yLbd/rFo7PdwbueNIvYqhg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
