apiVersion: ENC[AES256_GCM,data:P1E=,iv:ibpvRk+6uVBNqlL5/RWX2HOkGrIHWgwAx8vMOcWhtbs=,tag:8qbEwLHCZmrclDJ4okkUXA==,type:str]
kind: ENC[AES256_GCM,data:HwXff1FM,iv:QEcnSSUidWGnw40aH9uTSDx3SQF2SxkNKWNrW1mXLGs=,tag:MYG4cX2mwU2qe9tqeGJxwQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dYmSLLMu9TKmZ6cNQ0hTDA==,iv:Zw/peQBZEtHDfToMXGmBoPO2E0fJTgw+BjCOSv3CfI4=,tag:fpNK1BOWDMDlTAZ+cQ6rRA==,type:str]
    namespace: ENC[AES256_GCM,data:8qyeRTK7B4FoxA==,iv:+ueB/TsJFOPM5eqfEWzcn+EO/bFBs6yxDfjhjnXRcHY=,tag:0T/PMbYwgqLjF35AlUzBow==,type:str]
stringData:
    username: ENC[AES256_GCM,data:3wFz5HI=,iv:O9iA/re06EI8vV7CFX+pwsQN48xETjnYgX6paB1tLsU=,tag:v1bxJMXAaHqRbFpVM7Q55w==,type:str]
    password: ENC[AES256_GCM,data:9oQ9Nxp3LCy2xXqAvrJOCG+Ec7Y=,iv:2p+8mprgXevbpbwx9jiYVsDs955vvw2rTp5CWnQxTOs=,tag:V2zbR/4X3RxvC+6NXJHeuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajlMZStkRlJNTnc4ckFH
            RWhLRm9xaHRON2NEK0dpcERLMlBjRGhnd1NVCnplZHd3YWpISTlEd2JuSlVVWS9P
            anpLNzVLWkVtZkZjQjBlRHBQQVlOdFkKLS0tIGNBL2pRaVplZ25RWkNUT3BHNndr
            cGhBWmdEenlFQVlJN3MzS1g5WG1BbzAK5+J3DitREevQXnRM/ZK1O7K/TzbVcSFt
            Mqd8JNKrwC+yHewcyEcqdifU2G89+HVNjiMe5S3we9Hlavyg4PYMww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-06T09:48:21Z"
    mac: ENC[AES256_GCM,data:33eYVx5VymozClwsxf7vgUztoM5WdRT2ixyvj/QrMh0lbHKgjoenKt5eOu15kuFqxNEWRUt5f8H4VPz9ccwGVA9JqXxUIXj0HN7beFa+WVTuMIGhROScEupE/lpZgL+L2+33MXh36K8OhaUP8tC2XInqqEliqh80K/TcqQSGsG0=,iv:enQzbfMSdKAFIG6jqMrsUk7B65q5y6EV7JGusQhGpG4=,tag:gMM1sqqtlka+UzQaZ1uNuA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
