apiVersion: ENC[AES256_GCM,data:S8c=,iv:42H0140fibUXzwfvkG+IFILsq4bV637OXSiqhIGPzc8=,tag:7iZ2Dj5TOcXIKFTK7g07nQ==,type:str]
kind: ENC[AES256_GCM,data:a+mCTcyG,iv:DMBny/y4pmQrJIUYhBIP4tKjuD3/CzuQfXh6OLfTu4M=,tag:CFcxAgba/vk1lpmwiNcnDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:K70iDCyLo/TOwB5bcRCIPUN9XQ==,iv:ewJe1vLpXTJfaD+wixXuoofBhPDcSr3Hdvzu+TPXq44=,tag:c5uZy4QXLQI8k+Y1MN52cA==,type:str]
    namespace: ENC[AES256_GCM,data:j/92twXH+8pXbw==,iv:cqPFx9MOStbBl+HUpYKOsnoD8hO6og4sAUoFn42hZbA=,tag:shDDNyxif0IN+BL1IHyc5Q==,type:str]
type: ENC[AES256_GCM,data:ILMydxKD,iv:r0+tudVtSiMH8fVLr0KCiwkkKk3U815ydBxrCw+vJ2A=,tag:wQkqJ4uvFVyRTuaEqkZH2g==,type:str]
stringData:
    alertmanager.yml: ENC[AES256_GCM,data:qm/B8O/cti5GDq/yXsI6hnWaVaWLOEnP58KJeGPu8PAJp8Zns+2RnCAbAPOjfS3YZuvW2+Co8ckBzNnune0fwHcPK5EMkvIMJgfc9xl+dKKQ1bHLY984GUpsrWbPt9fu2EAMDTqX3epIN6gmwwfrOQnep+JuT0eafby0O8zUzgPZ9/xHuSr4pwXGA3J1Cd072JOebseDt3gZf3mHOZDxBqNkaYQkdFhRHlibEU14xUnfIFJhEQPnUmfYgUu0k4FFmd8eCUiDkp66kYXGbMyPzU/0fd8HbaXgB8QTZnd4lSsVEG2zP9eakSMIOD42vzoS94N5kkdIxBWXj8w3YMEnyXMaeeOwsNjy+FGGfHBaRMYWsT0fgXXn96V1HoGasLfNBnjY9H+JoxFXECYH0moZOLyur+/wPkPAJ9xaMd7dr/L0/0eDQjTHR1Y1o0iEWy1UmUDTl+sanKSs/Hkr1AR2sNGi1/RdBwL8juWd78Vq9YJH5ldz/Jrf87OnDQD+x2hAj8TJikuAxDsFiJD6da8TbumKl6q5mrG5pKPWny/a0okubyfXOa/EVEf6EK+w7Wmkd7zQ12cBZHi3WfQX0M3hvRfrjf3RPJ6X0X3hTCDC9l3GtosCZZMn1hgLXE+7OBYOvu/qkDLTmtvp2CYtqxB8PcoNQYpGlGq30SOTwfsO8FcnbEW976ZoK/3X/HfRtyvDqfjwp9jjVzUEnjFHCwZ1hGi7y/L/cumPM+O4XLQ1k90Osmss+EXpNjmvpMAag5BrIdR5c2v3uBM+hm0Wpimr,iv:7IDatIdQdjioQcKuitB2BKnxSohv7V5nlx8msiE1Kj0=,tag:ALVqixiUZ6dw4PrdiMHekQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SjByVjNqRkVQZS96RzdC
            MC9KMUl4UkwzcDk1V1pRN1VhVVkvYlVxU3dFClUxeGgweE1XWE1GNC9PK3QvTXkr
            bWJRWVdkRkw0MlVzRVc4VDBQaEU5Z0UKLS0tIEg1QllCS1h3YzI5bGQ5NDk5UFNG
            ekhIa3Y3MDZkL1E2MGQ4bHE4K2cyL00KBgiP3/Npm/jISWpj1V+U4oodZYAaR1dL
            49G7IL+Ndu2Ecu4kwjeIGYnNf9lsuuPKGKWOdqzyUdY+N4CAM8LpOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-11T11:41:40Z"
    mac: ENC[AES256_GCM,data:sXVbyCFCH2PXrk9hUnM/Px8x4sylQskY4DaQLWXElEZEKR8i6ZdgsyqdiTGp25hS/oKAMG0a9cDoB2fRO3wI/qV4PfBLsY5W0QTW07XaySPHF3n6xXuVDMt8GMKTLdBBzdsurpQfpH7YuRG39+9tfu0kE2xZLnzyWZ8zMUoGC/U=,iv:1OzjcqgclTpW+N4U2AcHPGsOb3nrnfNnTH66By8csgQ=,tag:GYqbtREXHLpKJ/fmDmF+wA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
