apiVersion: ENC[AES256_GCM,data:XNA=,iv:Rd3tcrW2RRHcCtrOWf9hdvy3l6bQ2Q3rtK2OLu3TxlQ=,tag:AxxVn8qMBJD/Zb8yrYJCFA==,type:str]
kind: ENC[AES256_GCM,data:vibp4OZm,iv:m5Fe4ouFeRxvOOF5rcCHHQnyp6vnu4s5+kGP8o1i4s8=,tag:P0OxE/0cEgNakuebzU7cWQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xlMPD/imJqE1YWHIZ7p4I3Im2g==,iv:vS+i65D9i6gEnR/MsPhWMt6u2M9Epp29O2Z/E99PzH4=,tag:uOmOqeqX2HGpwFgTCGCXKA==,type:str]
    namespace: ENC[AES256_GCM,data:PRs0KuBMG801iQ==,iv:PVOHLuIi6+vjBLHsA6ofvRvBUarw84vpD/IIKkOEgho=,tag:Fzs3DwEaYycVifRhxR52SQ==,type:str]
type: ENC[AES256_GCM,data:+8oMbgpU,iv:byn9fiSWtOKRZJ0o6gd/zU9rD6XwLg3RCyrDTurAqe0=,tag:dzRDcC7u8h8rJpoJYXqUuA==,type:str]
stringData:
    alertmanager.yml: ENC[AES256_GCM,data:tKkGngAOghBZ+FuIHoCWwFxKLo2FrQOVZ012M3JjDwT6Z/KfM/zZ112TOlkTc51/g81REeMXyHEfy47GGF8n7zgPSsWAiQAG52m6jo1kWK2r6fsNKWdCA6O7jkhDi8KyADRI336vspBiXbu1dAm29lg2yogi6Y9y2YDrk9HUKdKM/zekuNusWMwbeSLp2WgbG2OaYwTvC5hlLQ/C0eVS2YDLcg8yCwMDFiWISB+WI1Z5qXCZjBEaRdbBx2JYDEt3B5RzQWbVgN0Me0/J+Lb/s+Lj0A7pli3uagg+q73/aXeW/X+rmepiuwzYFkoB5mr419ZJV5aI3CeNcFClUn0MjlMBMNBMAgPRD4jAfpj03B0zBFJvkk4k46vKV8QRaTB4UzpcoLZ6whtsF7GwrvQbtVW+ez8kzZR7nDlUQWJB8rC2ukZGxmGAa/PU5chUDrcx1k4ezx+cNwm63ujB8szv4YW1olWmlCEMNL6glNkG0PMYbkYZg6GeDR7RbjwjIFFd0NQxc24vQKPIX+D8eP8PO1tiVoCrrsnRDr0Oyn9j04moazx6fZv5uL11Ru/TZYGpiziLRXOnglCzfukHrOo9nACwTg0ApPlMm4JxRdN5xJ2CjkpGBVB07P2fCm7b6oAsxSd5uPMhJLpNLCkH3K9LtWNbLTjiC3/c69Fk+vwYnF79g//Bl7poqftwXqkv/qML2eIWpmGddm1QVp3PkjDKE+aACJNVl/ANDgnPLpCAhaW8xdzTdU91dXkjOKEEZA==,iv:J7/ph7wq6bw9X+GVt1KskOiv/b61sXqDhH2SS58FuRs=,tag:gqhckgd8WoKv09pcE8LlGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOWpRQ2VYanBCYUZOcTg5
            ZCtzMTZtbFFySXl2WURwcUNuN1RkbDYyZDNBCjR3b3hySFN0RW5EMVhyU3ZkcVFy
            VmJyUWlmVzhpNEh0UlZYV01DUVFwL3MKLS0tIENjNEpEVzdtYmdTTk5TSTlJQkZF
            YzZRYk9IRmRhYXdaL1hZUVVEYVNvS2cKA7tbmWhBJJRpmYO41wFVYO+8SVgvqvd3
            bARwy5tB1ocRF26TuKOyGgEs+AxSUGXYwnzh/VGGTMmSbGFXMeN93Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-11T12:11:51Z"
    mac: ENC[AES256_GCM,data:c68L6pIIi5F2pi4B49CdZjHuq8s5KCu5ksMlYFt4IA/40hasdzDcpPocQYjzMHVDE2M+U6J0bkQT/9iZ61heGDMNGaLVKVoQmL4s3cAjBgvn0Lgzm9tZif1UFvuJkS2eSeVpWn+f6w1aWsakQUKNn4FFdATcvc9BS9OSctTU8rs=,iv:weaQZ9HItECEClyhDPv+9qLxSv6FoP8WnBVMDJLXItY=,tag:KIWMUBOZywYCsUvG4xgYFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
