apiVersion: ENC[AES256_GCM,data:F34=,iv:UHCIcCjxe6L0X3xUO3Agr6GsAweaBQh0nTk+LE/8nuU=,tag:WxblwjytSyPjywjfoQp9DA==,type:str]
kind: ENC[AES256_GCM,data:o6fwwVv3,iv:BQOpkW8zEA+ER0+ntbEpLFL3LXoSz3fFQKXruVKoN+M=,tag:Tv1JwdwY4VgrlcKzvBGwRw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P1OtmJ5TE/GhGKE=,iv:Ex3P7Xa3XYWJtX7vq8uETSVO2qje9shuaDbZQQDl7pA=,tag:ojMayOXC7OzYoYHs6Py2jg==,type:str]
    namespace: ENC[AES256_GCM,data:ra5KvFbLNw==,iv:Fw/pkyr4MnEFVz60w7stZs0aLK1AdpYWtctjcc7C/D0=,tag:n4odEc6mZolnRFSVGEfh9Q==,type:str]
type: ENC[AES256_GCM,data:zFyXlI/1,iv:3cQnH4kl/yu/z2qnZIx+zf8Jq7kAkgP0n8yb8EKKZx0=,tag:UzxgBwLu5dUxwB/pzpt3/Q==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:DtoqMk6WgLihZL8zGOua4FOqy+BPuDoZQWOzgjbD3uQhSrOpOq1SbUyxzNwpJtZloyQ9kP2CFK3IEP7hfAVfaB8JCIRhbS0BwNH/Ga/sKzybiPYwV0bPPzOJ,iv:Dn5L5siTMYnamFuJuxOfhf8SDUQJ9FUuGPtZCCrd2+s=,tag:MGxM6j1RLOk2dNr3ukw3Yw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:DgD0iJ8UhXjBYiS/0ybnah/T3md7a5BaP+M3agIf41t8uSadmQna/Vshi5d+XA==,iv:LLhtklq0iWW0jkmlcdsnE4FnG+vo3ReQv1kf7Jw+koo=,tag:dXtaUcHoXkbfDG04grJkdA==,type:str]
    API_KEY: ENC[AES256_GCM,data:5q/nloUNFB/CwpxD1GdosuUQjiW6W4e+MtNLoOoPKn/bhg+WTpdcwfHNIu9Jt3y2,iv:7nUakKSAWz18xTvqBQ3NVpjt+am+m0eQQMxkTBmVWDs=,tag:gF1SVygyJrfq+AtGbtnnIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ29sMHZPbS9JQkYzb3JF
            WDEvZTl6ZS8xRnFSVGlhUXNXNEd2NkVsYjFJCmpjRi9VT09tQXBrNDZqeUFRWVkw
            VThzZnJranNkYVlaVHhFekNFOEpUa3MKLS0tIFprL1Ria2pSMHpUNXRMcnJnSjN5
            VUgzNzNCWWdvbHNkMHhQRTlTT2NyeTQKJHa/yw0XieMQrpOLy/G97n5dQt7vEg5N
            3LWAm9FHrODo97aZ8cvIFU0yReyBRZcs0FUBYHLcQ+LAeQ8fTB4F5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-03T09:53:02Z"
    mac: ENC[AES256_GCM,data:kcephcGXXXEtAlVdvAMN9X+kDWMtNpz3yTWkx9FhLUzL6oqD3H1c6SR4Gd7V6Ja4YWcZA3KVhlBd7EMBT7FsThR/KWTO7ikO3ZwugZEm9Eex8dkw12fqlQkHOA54DO3vuKzl2lJMDOrkYuWtlvENHRq0kbylhHyb47zTKoWAawc=,iv:Hp08Wue9VINAWQnVgfzxK0MSh5Tz7pfZQ5ngrmPGd2U=,tag:LwJfE9td+bR1D9vcPyTDcA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
