#ENC[AES256_GCM,data:WGsoStJTFy86wcwyiJz7xzi8crjEjW1t/rLpU+HIH6VlfCT2PpnLQwzpewLlroHq/nbYSJSqHHlKn8kiP/w7PXem/tsHwC4=,iv:dmoKCHGTWY4MN5/cwSA//BfAMCR+gO0GWxct3RGRpL4=,tag:O7Yk9ttE9aofIxHY5eJS3A==,type:comment]
#ENC[AES256_GCM,data:gf1fgU0/E93YV7bBhVxI8PnB4iS34V3X/HNlmqBuKtUU+IQHndBNBREGhdU/rb/UoX1EVFqofKV82r/HlA==,iv:eP104jNG5rJNEHJdBcRphezX4dogw8fDj7nJpm1WmJ8=,tag:dc33jfDe9Nxcb3aH3qxNpQ==,type:comment]
#
#ENC[AES256_GCM,data:ex+pCov4vrv0dkj9evHsRAbK+mxdit2pbK804kr67Bd9fWnhIUqjQEkn9vb2St9g5PDi6SrNASagZ8TeFkMuV3S4nrHZECQ=,iv:ZNXYvjbAYaYp0JlVAbufItPe+wbpkGzTD6B1FmY5qCw=,tag:18TBIXxX28LnVL6jTenbvQ==,type:comment]
#ENC[AES256_GCM,data:3700hZ07TTDmJTx8b2nvAB2lVFp9E6nQd/fHIrb9+4HxwvqkHTKcbzcedzBZtE0IU82yTYnAt4VsYWgOiXGE8UkGlHDQaq4=,iv:C3DR9TmusiUi3MiaPc4Pj0XQ2qNEagBEsBWjBWCGjtQ=,tag:vK4l3M5/Xn84NkBQiq9o6A==,type:comment]
#ENC[AES256_GCM,data:p3UC35pPIxvQG4cry1quMwu/+DBdYAfesBibUvmU88NIOr/dbRVi1fp0CAI8dDN6sAWYlrIGyPylUsMDE0oyM71htKAuhFmb,iv:9dxqK8vmELAtlzUj1LJ8KDlmovtiQBgKAmrOwZb5lMM=,tag:jOd+uDfK/9y0MCg2k5Pcgg==,type:comment]
#ENC[AES256_GCM,data:LYGHece0MBXzWW4guP/p/MYqGwQSTjSOvISFnLQordt2jaw=,iv:FkCjHGQ9TYPbTB0Ckk8ZcQDBXcSmCE0YOGWF6GAEbfs=,tag:u2t6iYMaWI00TGcaNgxO8A==,type:comment]
apiVersion: ENC[AES256_GCM,data:A9k=,iv:CnmTDbRsKlaliRztwInNs2AieyW8cAhCSBPRdBFVKeo=,tag:8T3GM9i1YUaB9M9rJhvoLQ==,type:str]
kind: ENC[AES256_GCM,data:eLIAA4Cb,iv:zKbiWmz/D9fvjLd5R9jdiZYUiUpqHbtNeWyFYg3pJ+Q=,tag:znH8ojASV9Ee0UjmlHxskg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CqNPpaGOr2kJUJvq,iv:SB13oY66S+/kk3r3t4xhiCJagBw273CodKepXbIb0vk=,tag:Q7C8HJ3sQnpk5kpX0KaQ3w==,type:str]
    namespace: ENC[AES256_GCM,data:Hzukiw==,iv:6IPE2QooF3ST06u8jtMMVx4URxWrA6/4JQ67djHY9uQ=,tag:acQcuDAsA20PK8BWzgoQUg==,type:str]
type: ENC[AES256_GCM,data:nnCPRgaB,iv:TbE/iCAMCvlboSRtlXJJHjrdA2M+vREtQJqDgZaD1VU=,tag:N28do1LMe9HiVILmwvyhrA==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:enIFrr7qeIVmNX9VhYFyeVNGO2y8sebom6cfKoBHkZ7QdtkTKtFDKAXW97X+b3XG,iv:mYgUx+KDwJSb/DkPzGW/9nasHI70J9wc+hkJZSEueHA=,tag:rXQ3UstdvURAhwyF3iDicg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYW1UazVYdnRYZk90MnNN
            aGhiTWEySU5QaHQ5ZGRGTlZXNGQwaElHN25BCitmd2VkeHFkMW1HZkk2UmxTbmVM
            dmxXREd2cjFEZU9QaTVQaFJwY1hUZTAKLS0tIFpTUTNVWFRHb05pUWdqR3l6UGhX
            WWZuakRNZlJxYXRwWEUzOHhUeHhPMVEKMWp+YP3PVeacRHh3zPRW+wcEak6yFU2q
            Rvi2kPFXJGENWjn7ypF4zy02A3vRDmiYo4BhVICfhKQoYF2c0FJF8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-12T06:26:44Z"
    mac: ENC[AES256_GCM,data:dAPjJj+ljG1bK6tPD20aWY2+NVjJP/jUMy2NimULAdTMIviaACEPgoIB/dOkLhUAhXoMHBDbWCadV3CPEQ6JGF9dMTWb8oz9O3gl/Ysg30gMzzHFUcTgP5Mz1HfW40IG+wRT2FzqaLmlwa6k+uYa7HECyxut5Ehg6b/eOZoM4eI=,iv:I0iQ/SwUvDY+RH5Xcon57lmZdstV9HIi5PaYZ1W1imM=,tag:lfM3PQ+OjQBsTExHHUnROA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
