apiVersion: ENC[AES256_GCM,data:pKY=,iv:DHDaRp/AsgYs1dxUfpPlz1bGK0QemVTuxJ91wivGWbc=,tag:rpf3XNMpkhdaSqaYT/EDGQ==,type:str]
kind: ENC[AES256_GCM,data:7wFZ5PyQ,iv:TOJp/KDoNJDaItgMorgUIPBZrqJUxx3giLDV0aU5pqU=,tag:D4h05VOv6lUK+mU/6Fhv1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NwyHHeU/5+GBYqCLew==,iv:v67/3oH4/pA4XtFmF8iWfCFzwhHdFi9aVufiSp+Tfv8=,tag:+h6lJ+DoEre5hQfWNJivMg==,type:str]
    namespace: ENC[AES256_GCM,data:tT0PDKIvt0R3mA==,iv:N8xPJTfZtFYziiGt+haO3XWe3FxasalKBM5oM/bo5xM=,tag:7URXqxhQmdSgqXU6AlL0FA==,type:str]
type: ENC[AES256_GCM,data:1kbyQpFi,iv:aPnXWX9nCLpKwWvpzYXpSiCYFxxOTQ8rBvFZyZsUbJI=,tag:JwQjqtlRspMp1Noj8dEKag==,type:str]
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:jSVdhPi7pY/ND31JXVgD3+il,iv:eU97mnvEYEUccrdz03bgz3LHh7luxWG9zDfX1bcaCeY=,tag:4sE7EjWCssiK9FXkrTaaGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxclNCRUZQbFB3Q2paUkJ1
            TjFMN04yWjAxVUVoK242VGJpS1B5WWRjNHhZCm53Z3lZQUNTQU1iRWtTWUVMQ2h5
            VEtoQ3REdFpZM3FvNStybVV0N2FEZmsKLS0tIDA3eVdsQVk0Y3hDOTN6VE5PRkFl
            MTc1L3JibUZKYVp2cmpWczR4UlRhZXcKpj1AM+ErPKXwkeCPOGsmTMOaFlI6bmXe
            DXYdo6Ke1YAwrUp9cZFOoXK/T78w8rSxy1NJ5kDkKlinvg+dqbo+OA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-03T09:53:02Z"
    mac: ENC[AES256_GCM,data:HcP8aWv2SGlPYCDyHolXmGw8DDKG26r6YTXtwlRxI0kq3km3hKNCMoZd0lgfJNzGHzLZ75tdA1UTrtTW3DloICTVIbJeF5182RCH2ozzqA1c3HBp2ls/a4aA4+MUZoFK/0gGoJsTM61kSvv3Y+Z75VKcTeK8AS7EKQfTSr/HQTU=,iv:gspJxSyoU2/h2xM3I70+SboT+UN7XnkvnBh6nXNlBko=,tag:jYzrAjM+9N93A+zZvT2U3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
