apiVersion: ENC[AES256_GCM,data:9kc=,iv:8eNorAFnLlixgdJpomqXxAVhBnIAk5viqDs9iEh7Txc=,tag:O5NkAjwO5wb/xg7EwqNBQA==,type:str]
kind: ENC[AES256_GCM,data:P6WMMSwy,iv:1xEbF8T+W8BGzLRNRrm3ziWdMLPONrD3XFUreuwBD2k=,tag:E2cYRcnVmfVMCLt0KY/bNA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pWAHorYeSSsl8S9GkNBxYOEDUvw=,iv:xVHVXCI9zyfqzenzxXX/9lIpgJ3lNXznPOD0QE6so8c=,tag:S8TmaH31H6K+OehhkCR5Vw==,type:str]
    namespace: ENC[AES256_GCM,data:5C/NkQ==,iv:wFHhr8X+iOdF2Wj21J9NR0wwVttrBPpjO90W0sxyqmw=,tag:h02TYGhHfE1AL/pJFm9cZg==,type:str]
type: ENC[AES256_GCM,data:3JPIZe6l,iv:VFa5aGAVtmi4/Wr9U7fBI/jbUqCdatl6TwK8TkcmUdM=,tag:35ShxgN3i24KXx+FDJJUEA==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:FwTXef7FzA==,iv:u+/HZYwABoZDJXRvS1P6Gcc2CLXH358RMcmu6U/2Edc=,tag:NGVX8PpGH/c2jt4hRl9AXw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:04ZQ7QVMdVjoX8hVpDEps4mMBhlfi/Rj,iv:xcAQT1NhVe9rqoSgVQYPhwEsjvieaA3o4eKjxPyJuQE=,tag:1hKTRwo8SDuvg7MANO0hMg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:ke/xQlzRmw==,iv:aabQto8EoB8JraeADl2m6qE087zbM8mFmwz+FKPrlI8=,tag:1dAivdKpOFDN8XTX+Us8HQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa2ZKbklTZ1BuWnFZYUtD
            dDZPSFFUV1k5aDkrMXZKZURhSTMyN2lyN0FVCjhiZmpZSWNrVVVjczNlK3ptcWdZ
            OHZMWHNVbUxObWI5Zld2VkJaOTFrMlEKLS0tIFhqNmkxRWRaS2FBY3JYc21hVHlR
            bFBxWXVFbmdRS0Flb1RPbDhUb21ZN1UKUfWTqbEjjheGbcNLDASNExzLe0sJYbrt
            VlyQS9246f+lKU/HSF6AmAXhLeGd+wqCWB3g+IVDNpIbv9W5UHrT4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tsns9fmhenrdl5ufs2vs28gut2m464xlcp23440uxp4x3aqvdgzsytyjwx
    lastmodified: "2026-09-03T09:52:38Z"
    mac: ENC[AES256_GCM,data:A1UnSCzWijFC9NRSM6aRC9w0Lof8eG7PczC7yoZLZAKafbGqN/MXN6a+9DU/TWZNsknETzHOHa6ZEwOYacJ80kCEC0Jv+OX8d3MP4MkHKLsmW/4Ck/hX/FwaTkxgRe7LHC1XMNdNNaGE7mDkS2r8fq9cLtOxTYC4eFIzK3Bq2M0=,iv:TKsUYjAETFilSY7ECf8Btwpov/YM42iyd1mvk9RM1lk=,tag:2pI+3I3jnfd+RFzu1OWbXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
